name: Notify Infra Integration

on:
  push:
    branches: [labs/lab2]
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: send dispatch to places-infra
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.INFRA_DISPATCH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/iREALLYhateGit/places-infra/actions/workflows/ci.yml/dispatches \
            -d '{"ref": "labs/lab2"}'
