name: Frontend CI (Lab 3)

on:
  push:
    branches: [labs/lab3]
  workflow_dispatch:

jobs:
  ci:
    uses: iREALLYhateGit/places-infra/.github/workflows/ci.yml@labs/lab3
    with:
      service-name: frontend
      docker-image: shuasd/places-frontend
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
